# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: yutil
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=amplia-iiot
release:
  prerelease: auto
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE*
      - README*.md
      - CHANGELOG*.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.YUTIL_NEXT }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
